import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppWidget from "@/components/WhatsAppWidget";
import PrivacyControl from "@/components/PrivacyControl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <PrivacyControl />
      </head>
      <body>
        <Navbar />
        <main>
          {children}
          <WhatsAppWidget />
        </main>
        <Footer />
      </body>
    </html>
  );
}
