// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  chi_siamo: dynamic(() => import("./ChiSiamo")),
  gallery: dynamic(() => import("./Gallery")),
};
